name: Release to dockerhub (release)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
    release:
      runs-on: ubuntu-latest
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: sweagent
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Get release name
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
        - name: Run release script
          run: ./release_dockerhub.sh sweagent ${{ env.RELEASE_VERSION }}